### ISSUE TITLE
pre-commit catch for embargoed structures

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#538]
We should do a better job at catching confidential structures before they're committed to this public space. We'll need to build something that:
- grabs the list of confidential structures from CDD (both VC IDs and SMILES)
- for any commit, checks if there are any matching VC IDs
- for any commit, checks if there are any matching SMILES/ molecular matches
- for any commit, extract ligands from PDB files and do the same as above
- reject a commit if a match is found

There might be edge cases such as ligands living in JSON or other formats, but catching the above will prevent the vast majority of leaks.

**Comment by hmacdope** [comment]
Tagging @ijpulidos

**Comment by hmacdope** [comment]
Having thought about this more, I am not sure centralising all our sensitive information is a good idea. 

Here are some initial practical steps, the rest we can discuss in private. 

1. Add all .pdb .mol and .sdf extensions to gitignore so that they are hard to commit (must use `force`)
2. We should pull down datafiles from an S3 bucket rather than have them committed to the repo, that way we can yank them at any time without having to rewrite history.
