### ISSUE TITLE
Standardize approach to passing documentation up to the higher levels

### ISSUE THREAD

**Issue by apayne97** [asapdiscovery/asapdiscovery#907]
For instance, if one wants to understand what the `--oe-active-site-residue` flag in the protein prep cli means, the path through the code looks something like:
`workflows.prep_workflows.cli`
`workflows.prep_workflows.protein_prep.ProteinPrepInputs`
`workflows.prep_workflows.protein_prep.ProteinPrepper._prep`
`modeling.modeling.make_design_unit`

And this points you to the OpenEye function which does the actual work

In each of these places we have potentially disconnected / separately repeated docstrings. So if we wanted to update the docstring at any (preferably all) of the levels to include the OE format that is required i.e. "HIS:41: :A", we need to track down all of these places. Before going through to update the docs I'm wondering if there any standard ways of doing this?

**Comment by hmacdope** [comment]
No standard approach as far as I know.  Some codebases just don't document the low level API, but IMO this is not actually useful as we use things from all levels in various spots.

**Comment by hmacdope** [comment]
I don't think we are going to come to accross a tool that handles this, at least I don't know of any. This means IMO we have one of two options. 

1) Status quo, document everything at all levels 
2) Document only the highest level (this is a bit silly as layers are often built on top)
3) Document only the lowest level (this is silly as the )

I support 1) supplemented with lots of example notebooks only because reading code is difficult and slow and more documentation is good. Sadly labourious documentation editing is the by-product but that is the hard part about having a useable package.

**Comment by hmacdope** [comment]
Closing, as we wrote great docs.
